# Generated by Django 4.2.4 on 2023-08-12 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0007_alter_game_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Human', 'Human'), ('Computer', 'Computer')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('MoneyLine', 'MoneyLine'), ('Spread', 'Spread'), ('OverUnder', 'Over/Under')], max_length=20)),
                ('spread_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('over_under', models.CharField(blank=True, choices=[('Over', 'Over'), ('Under', 'Under')], max_length=5, null=True)),
                ('over_under_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('selected_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.team')),
                ('tipster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips.tipster')),
            ],
        ),
    ]
