# Generated by Django 4.2.4 on 2023-08-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_alter_tipster_source_alter_tipster_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='bet_type',
            field=models.CharField(choices=[('MoneyLine', 'Money Line'), ('Spread', 'Spread'), ('OverUnder', 'Over / Under')], max_length=20),
        ),
    ]
