# Generated by Django 4.2.4 on 2023-08-12 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('number_of_teams', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='games.sport')),
            ],
        ),
        migrations.CreateModel(
            name='TeamAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.sport')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='games.team')),
            ],
            options={
                'unique_together': {('alias', 'sport')},
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('game_time', models.TimeField()),
                ('scores', models.JSONField(default=dict)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='games.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='games.team')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.sport')),
            ],
            options={
                'unique_together': {('game_date', 'home_team', 'away_team')},
            },
        ),
    ]
