# Generated by Django 4.2.4 on 2023-08-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='short_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
