# Generated by Django 4.2.4 on 2023-08-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_team_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamalias',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='teamalias',
            name='sport',
        ),
    ]
