# Generated by Django 4.2.4 on 2023-08-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_teamalias_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
