# Generated by Django 4.2.4 on 2023-08-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_sport_short_name_alter_team_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='scores',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
