# Generated by Django 4.2.4 on 2023-08-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_game_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='favourite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourite_games', to='games.team'),
        ),
    ]
